language: scala
scala: 2.12.3
jdk: oraclejdk8
script:
  - sbt dependencyUpdates TableOfContents/test
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/launchers"
after_success:
  - bash update-readme.sh
env:
  global:
    secure: bshEnZ/8Wd8McP8vg83FJaJHPUtguNudrP2rN6nQB5pUCyv+2zOoQ/ZOm6DTaLhuFVBVuaeNfZNPOtObBQ9ggmGarvuZx/KdfhrX+mZq6RlUtkM7APb0cPk/xnZfon+aZKo046uJAMyrnFMuJOL8/w48Gmreb5fe9sPJbC/kaNMbp4UB1bswAiLb56FHkt1tBfUQrXLuYFtq/VrOAKbVzy5LBM78S2Ex/ZUzcPW1MQYnu68uB/HwwW6ri4Mz5qvCwuVwjMYM04LuYjX8rPof1SnIJCB5mC2Tt/iQ1Jc78Cl5yKrRbnYT31L5+Rc3v7ZHSNACn8KDLcY2GmzvGz50Bds4KDSYUDEOnCFigXGS18msTHtqUKVXSkervsFxLtyDh7V15zY8KBWGxhgzx7iOvsszFTiksT5OxGU+uN6HVp2dDMGauTFFIyQWPa0erOmk+adm8F/dEluN4q15mBD1bkRbBrfQMnGd8QG+YX+23xRyyG3fEzlO5AUYfN7jLVyQQ5cCkcm8qX6wKwbYZfNElIiS+xvoADS6QZi8gdeLvwHdN4KS5YjVl9gLSx2LkVOqu171NSBouFzLdS48PqS634qQ6PkzD22VvoL9pvbct12tPYs2x2dW+fb4M8svawDM97HQQabCxHlYk1AG5npl4Zt9IyBGObX3E3/ad7Fv5v4=
